from setuptools import setup, find_packages

setup(
    name="frame_gen",
    version="0.1.0",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    install_requires=[
        "numpy",
        "opencv-python",
        "scipy",
        "tqdm",
        "pandas",
        "matplotlib",
        "seaborn",
    ],
    extras_require={
        "dev": [
            "pytest",
            "black",
            "isort",
            "flake8",
            "mypy",
        ],
        "film": [
            "tensorflow>=2.15.0",
            "tensorflow-hub>=0.15.0",
            "tensorflow-io-gcs-filesystem>=0.31.0",
            "tensorflow-estimator>=2.15.0",
            "tensorflow-text>=2.15.0",
            "tensorflow-datasets>=4.15.0",
            "tensorflow-metadata>=1.14.0",
            "tensorflow-probability>=0.23.0",
            "tensorflow-recommenders>=0.7.3",
            "tensorflow-transform>=1.15.0",
            "tensorflow-model-optimization>=0.7.5",
            "tensorflow-addons>=0.21.0",
            "tensorflow-io>=0.31.0",
            "tensorflow-serving-api>=2.15.0",
            "tensorflow-gpu>=2.15.0",
            "tensorflow-cpu>=2.15.0",
            "tensorflow-macos>=2.15.0",
            "tensorflow-metal>=1.1.0",
            "tensorflow-aarch64>=2.15.0",
            "tensorflow-rocm>=2.15.0",
            "tensorflow-gpu-configs>=2.15.0",
            "tensorflow-gpu-deps>=2.15.0",
            "tensorflow-gpu-deps-cuda>=2.15.0",
            "tensorflow-gpu-deps-cudnn>=2.15.0",
            "tensorflow-gpu-deps-tensorrt>=2.15.0",
            "tensorflow-gpu-deps-nccl>=2.15.0",
            "tensorflow-gpu-deps-cublas>=2.15.0",
            "tensorflow-gpu-deps-cufft>=2.15.0",
            "tensorflow-gpu-deps-curand>=2.15.0",
            "tensorflow-gpu-deps-cusolver>=2.15.0",
            "tensorflow-gpu-deps-cusparse>=2.15.0",
            "tensorflow-gpu-deps-cudnn>=2.15.0",
            "tensorflow-gpu-deps-tensorrt>=2.15.0",
            "tensorflow-gpu-deps-nccl>=2.15.0",
            "tensorflow-gpu-deps-cublas>=2.15.0",
            "tensorflow-gpu-deps-cufft>=2.15.0",
            "tensorflow-gpu-deps-curand>=2.15.0",
            "tensorflow-gpu-deps-cusolver>=2.15.0",
            "tensorflow-gpu-deps-cusparse>=2.15.0",
        ],
        "rife": [
            "torch>=1.7.0",
            "torchvision>=0.8.0",
            "torch.nn.functional",
            "torch.nn.modules.module",
            "numpy>=1.19.0",
            "opencv-python>=4.5.0",
            "tqdm>=4.50.0",
            "scipy>=1.7.0",
            "lpips>=0.1.4",
            "tensorboard>=2.4.0",
            "tensorboardX>=2.1",
            "einops>=0.3.0",
            "pyyaml>=5.4.0",
            "matplotlib>=3.3.0",
            "pandas>=1.2.0",
            "seaborn>=0.11.0",
        ],
        "metrics": [
            "torch>=1.7.0",
            "torchvision>=0.8.0",
            "lpips",
        ],
    },
    python_requires=">=3.8.20",  # Minimum Python version for RIFE
    author="arielgoes",
    author_email="arielgoesdecastro@gmail.com",
    description="Frame generation and degradation simulation toolkit",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
    ],
) 